- src/Transformers/Api/Composites/CompositeTransformer.php
- style.css
remove cache logic from cxense transformer. Cache is now handled inside the plugin
> remove cache from cxense

- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- style.css
- We where trying to acces a none existing index thus php would crash
> BUGFIX: In some cases the siblings output exploded

- src/Adapters/Cxense/Search/DocumentAdapter.php
- src/Adapters/Wp/App/InstagramCompositeAdapter.php
- src/Adapters/Wp/App/PinterestCompositeAdapter.php
- src/Adapters/Wp/Composites/CompositeAdapter.php
- style.css
The value should be a int, and not a string.
> Set reading time to number

- composer.lock
- src/Actions/ActionsBootstrap.php
- src/Actions/Backend/PostSlugChange.php
- style.css
- Uses hook on_slug_change form the contenhub editor plugin to create redirects
> WILL-894/BUGFIX: post slug change redirects

- composer.lock
- src/Adapters/Cxense/Search/ContentImageAdapter.php
- src/Adapters/Wp/App/Partials/SocialFeedImageAdapter.php
- src/Adapters/Wp/Composites/Contents/Types/ContentImageAdapter.php
- src/Adapters/Wp/Composites/Contents/Types/Partials/ContentImageHyperlinkAdapter.php
- src/Adapters/Wp/Root/HyperlinkAdapter.php
- src/Adapters/Wp/Root/ImageAdapter.php
- src/Adapters/Wp/Terms/Categories/Partials/CategoryImageAdapter.php
- src/Models/Base/Composites/Contents/Types/ContentImage.php
- src/Models/Base/Root/Hyperlink.php
- src/Models/Base/Root/Image.php
- src/Models/Contracts/Root/HyperlinkContract.php
- src/Models/Contracts/Root/ImageContract.php
- src/Transformers/Api/Root/HyperlinkTransformer.php
- src/Transformers/Api/Root/ImageTransformer.php
- style.css
- Adding HyperlinkContract to handle links on items
- Updating all image models to include a `getLink()`
- Adding HyperlinkTransformer to transform hyperlinks to API output
- Updating ImageTransformer to add hyperlinks via the new HyperlinkTransformer
> IVD-216 - Adding links to images

- src/Actions/Backend/PostSlugChange.php
- style.css
Major rewrite of automatic redirect creation
Supports standard post types and contenthub_composite
Creates redirects on unpublish or trash
Test that redirects are not added in other cases
> WILL-900/BUFIX: Redirects on slug change

- composer.json
- composer.lock
- style.css
+ updated composer to add quotes (BenjaminMedia/wp-contenthub-editor#195)
+ updated version number
> Ivd 402/feature update composer to add quotes

- composer.lock
- src/Actions/Backend/PostSlugChange.php
- style.css
+ BenjaminMedia/wp-contenthub-editor/pull/196
+ fix infinite loop on post save
> Ivd 403/bugfix infinite loop post slug change

- composer.lock
- src/Adapters/Wp/Pages/Contents/Types/Partials/TeaserListHyperlink.php
- src/Adapters/Wp/Pages/Contents/Types/TeaserListAdapter.php
- src/Models/Base/Pages/Contents/AbstractContent.php
- src/Models/Base/Pages/Contents/Types/TeaserList.php
- src/Models/Contracts/Pages/Contents/Types/TeaserListContract.php
- src/Transformers/Api/Pages/Includes/Contents/Types/TeaserListTransformer.php
- style.css
Adding fields to the Teaser List API output
> IVD-382 - Teaser List

- composer.lock
- src/Adapters/Wp/Composites/Contents/Types/GalleryAdapter.php
- src/Adapters/Wp/Root/GalleryImageAdapter.php
- src/Models/Base/Composites/Contents/Types/Gallery.php
- src/Models/Base/Root/GalleryImage.php
- src/Models/Contracts/Composites/Contents/Types/GalleryContract.php
- src/Models/Contracts/Root/GalleryImageContract.php
- src/Transformers/Api/Composites/Includes/Contents/Types/GalleryTransformer.php
- src/Transformers/Api/Root/GalleryImageTransformer.php
- style.css
+ added gallery description and gallery image titles to API
> IVD-142/FEATURE added gallery description and gallery image titles to API

- src/Adapters/Wp/Pages/PageTeaserAdapter.php
- style.css
Returned optional instead of correct return type.
> Bugfix - Page Teaser Adapter

- composer.lock
- src/Adapters/Wp/Pages/Contents/Types/SeoTextAdapter.php
- src/Adapters/Wp/Pages/PageAdapter.php
- src/Factories/PageContentFactory.php
- src/Models/Base/Pages/Contents/Types/SeoText.php
- src/Models/Contracts/Pages/Contents/Types/SeoTextContract.php
- src/Transformers/Api/Pages/Includes/Contents/ContentTransformer.php
- src/Transformers/Api/Pages/Includes/Contents/Types/SeoTextTransformer.php
- style.css
+ added SEO Text Widget to API
> IVD-398/FEATURE added Text Widget to API

- src/Adapters/Wp/Pages/Contents/Types/SeoTextAdapter.php
- style.css
+ fixed null fallback value on SEO Text Widget
> IVD-398/BUGFIX fixed null fallback value

- src/Adapters/Wp/Composites/Contents/Types/HotspotImageAdapter.php
- src/Adapters/Wp/Composites/Contents/Types/Partials/HotspotItemAdapter.php
- src/Adapters/Wp/Root/AudioAdapter.php
- src/Models/Base/Composites/Contents/Types/ContentAudio.php
- src/Models/Base/Composites/Contents/Types/ContentFile.php
- src/Transformers/Api/Root/HyperlinkTransformer.php
- style.css
- Renaming `HotspotItemItemAdapter` to `HotspotItemAdapter`
- Converting `ContentFile` and `ContentAudio` models to NOT decorate result
- Cleaning up
> Bugfixes and improvements 

- src/Transformers/Api/Composites/CompositeTransformer.php
- style.css
reject related article if it's advertorial, and the article you're on is an advertorial
> WILL-908/BUGFIX reject related article if it's advertorial

- src/Actions/Backend/EstimatedReadingTime.php
- src/Adapters/Cxense/Search/DocumentAdapter.php
- src/Adapters/Wp/App/InstagramCompositeAdapter.php
- src/Adapters/Wp/App/PinterestCompositeAdapter.php
- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Models/Base/Composites/Composite.php
- src/Models/Contracts/Composites/CompositeContract.php
- src/Models/Gds/Composite.php
- src/Transformers/Api/Composites/CompositeTeaserTransformer.php
- src/Transformers/Api/Composites/CompositeTransformer.php
- style.css
The dataLayer require the word count number. Here's the implementation of it.
> Added word count as required by the dataLayer implementation

- src/Actions/Universal/Navigation.php
- src/Adapters/Wp/Root/MenuItemAdapter.php
- src/Models/Base/Root/MenuItem.php
- src/Models/Contracts/Root/MenuItemContract.php
- src/Transformers/Api/Root/MenuItemTransformer.php
- style.css
Adding a tertiary header menu, which will be used for social links on IVD
Adding class, link relationship and description to menu item output.
> IVD-428 - Adding Tertiary Menu

- src/Actions/Universal/PageTemplates.php
- style.css
On post save, we're not getting a site/brand from sitemanager, so we'll need to default to all templates, if no site/brand is set.
> Bugfix - Defaulting templates

- src/Transformers/Api/Pages/Includes/Contents/ContentTransformer.php
- src/Transformers/Api/Pages/Includes/Contents/Types/TaxonomyListTransformer.php
- src/Transformers/Api/Pages/Includes/Contents/Types/TeaserListTransformer.php
- style.css
+ added includes to TaxonomyList, TeaserList, and PageContentTransformer so that they're queryable with the fractal queryParams
**Warning: breaking changes**
> IVD-388/breaking feature page content teasers

- composer.lock
- src/Controllers/App/AppControllerBootstrap.php
- src/Controllers/App/SettingsController.php
- style.css
Returns the current supported version number for the native apps.
If it's changed it will force all users of the app to update it,
before it can be used. Therefore we are hardcoding the response
so that we are less likely to accidentally change it.
> IVD-437 - App Kill Switch

- src/Adapters/Cxense/Search/CategoryAdapter.php
- src/Adapters/Wp/Pages/PageAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Factories/CategoryContentFactory.php
- src/Models/Base/Terms/Category.php
- src/Models/Contracts/Terms/CategoryContract.php
- src/Transformers/Api/Pages/PageTransformer.php
- src/Transformers/Api/Root/Contents/ContentTransformer.php
- src/Transformers/Api/Root/Contents/Types/BannerPlacementTransformer.php
- src/Transformers/Api/Root/Contents/Types/FeaturedContentTransformer.php
- src/Transformers/Api/Root/Contents/Types/NewsletterTransformer.php
- src/Transformers/Api/Root/Contents/Types/SeoTextTransformer.php
- src/Transformers/Api/Root/Contents/Types/TaxonomyListTransformer.php
- src/Transformers/Api/Root/Contents/Types/TeaserListTransformer.php
- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- style.css
Updating Category output to support outputting content widgets in the API.
> IVD-315 - Adding widgets to Category API output

- composer.lock
- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Transformers/Api/Composites/CompositeTransformer.php
- style.css
Updating Associated Content integration, to use postmeta instead of post parents for stories.
> Refactor - Fixing Associated Content

- src/Adapters/Wp/Composites/Contents/Types/Partials/ParagraphListItemAdapter.php
- src/Models/Base/Composites/Contents/Types/Partials/ParagraphListItem.php
- src/Models/Contracts/Composites/Contents/Types/Partials/ParagraphListItemContract.php
- src/Transformers/Api/Composites/Includes/Contents/Types/Partials/ParagraphListItemTransformer.php
- style.css
The title is being used instead of the custom bullet field - removing unused fields, before it's to late.
> IVD-428 - Removing Custom Bullet

- src/Adapters/Wp/Pages/PageAdapter.php
- src/Controllers/App/AppControllerBootstrap.php
- src/Controllers/App/ContentController.php
- style.css
Use SortBy implementation to retrieve popular articles.
> IVD-428 - Get Popular Articles

- composer.lock
- src/Adapters/Wp/Pages/Contents/Types/SeoTextAdapter.php
- src/Models/Base/Pages/Contents/Types/SeoText.php
- src/Models/Contracts/Pages/Contents/Types/SeoTextContract.php
- src/Transformers/Api/Root/Contents/Types/SeoTextTransformer.php
- style.css
added image position to seo text widget
> IVD-316/Feature: added image position to seo text widget

- composer.lock
- src/Actions/Universal/Navigation.php
- src/Actions/Universal/PageTemplates.php
- style.css
Adding new menu location - User Menu
Adding new page template - Favourites Page
> IVD-63 - User Profile

- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- style.css
avoid exploding api if category has no sublings
> Ivd 316/bugfix avoid exploding api if category has no sublings

- src/Controllers/App/RouteController.php
- style.css
An issue where articles that are named the same across different locales is now fixed.
> Bugfix - Route resolving

- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryTeaserAdapter.php
- src/Adapters/Wp/Terms/Categories/Partials/CategoryImageAdapter.php
- Load data directly from term meta instead
> Feature: Removes request to SiteManager on in CategoryAdapter

- composer.lock
- src/Adapters/Wp/Root/AudioAdapter.php
- style.css
The native application is caching the api output, which makes the audio files fail, since they where linked via as3_secure_url, that where valid for 1 hour.
For now, I've removed the as3_secure_url, and returns the direct url, to mitigate the issues in the native application.
> Bugfix - Audio Links

- composer.json
- composer.lock
- src/Controllers/App/RouteController.php
- style.css
Adding parsing of the path to only evaluate case sensitivity on the path, and not the query params.
> IVD-530 - Case sensitive redirects should ignore query params

- src/Controllers/App/SitemapController.php
- style.css
+ fixed bug in sitemap where some pages were not included
> fixed bug in sitemap where some pages were not included

- src/Commands/CommandBootstrap.php
- style.css
-  register author fix command correctly
> IVD-470/bugfix: register author fix command correctly

- src/Commands/AuthorFix.php
- style.css
fix author fix script.... again!
> IVD-470/bugfix one more time

- src/Controllers/App/WidgetController.php
- style.css
In order to ensure that we get all needed data from teasers, we need ot parse includes and excludes.
> IVD-456 - Adding includes to teaserlist output

- composer.lock
- src/Adapters/Wp/Pages/Contents/Types/CommercialSpotAdapter.php
- src/Models/Base/Pages/Contents/Types/CommercialSpot.php
- src/Models/Contracts/Pages/Contents/Types/CommercialSpotContract.php
- src/Transformers/Api/Root/Contents/Types/CommercialSpotTransformer.php
- style.css
- add label to commercial spot
> IVD-526/feature add label to commercial spot

- composer.lock
- style.css
> IVD-545/bugfix timeout error on cxense plugin

- composer.lock
- style.css
+ bugfix add nl dictionary and check file-exists before continuing
> IVD-545/bugfix add nl dictionary and check file-exists before continuing

- src/Repositories/WhiteAlbum/RedirectRepository.php
- style.css
Fix for the error
`Uncaught Error: Call to a member function getStatusCode() on null in /home/forge/api.illvid.dk/web/app/themes/willow-base-theme/src/Repositories/WhiteAlbum/RedirectRepository.php:81
> Patch - A fix for logged error

- src/Actions/ActionsBootstrap.php
- src/Actions/Universal/PageTemplates.php
- style.css
- Changed Bonnier\Willow\Base\Actions\UniversalPageTemplates from singleton to normal class
- Updated to support version 1.0.1 of wp-site-manager plugin
> Will-989/Bugfix crash on SM failing to fetch site

- composer.lock
- style.css
- return empty if cxense wont return popular articles
> WILL-962/return empty if cxense wont return popular articles

- composer.json
- composer.lock
- src/Controllers/App/SitemapController.php
- style.css
Locking contenthub-editor to 4.8 to ensure post tags are added as a taxonomy for composites.
> WILL-764 - Excluding post tags with less than five articles. 

- composer.json
- composer.lock
- src/Adapters/Wp/Root/FileAdapter.php
- style.css
Updating Contenthub Editor to 4.9.0 which adds a new field with ACF for attachment captions.
> IVD-588 - Attachment caption

- composer.lock
- style.css
- make teaser list titles optional
> WILL-1035/make teaser list titles optional

- composer.json
- composer.lock
- src/Controllers/App/SitemapController.php
- style.css
- add no-index options to composites and hide them from the sitemap
- make sure that the sitemap sorts by date modified and id
- updated composer
> Ivd 622/add no index options to composites

- composer.lock
- src/Controllers/App/RouteController.php
- style.css
Updating RouteController, so that the full path will be used to find a redirect.
This should remove the issue where query params were ignored when looking up redirects.
> WILL-1084 - Fixing RouteController

- src/Commands/CommandBootstrap.php
- src/Commands/Sitemap.php
- src/Controllers/App/SitemapController.php
- style.css
- Added command to migrate new sitemap option on composites
- Fixed ultra slow query for fetching composites to sitemap
> WILL-1058/BUGFIX: Sitemap slow query

- composer.json
- composer.lock
- src/Adapters/Wp/Pages/Contents/Types/FeaturedContentAdapter.php
- src/Models/Base/Pages/Contents/Types/FeaturedContent.php
- src/Models/Contracts/Pages/Contents/Types/FeaturedContentContract.php
- src/Transformers/Api/Root/Contents/Types/FeaturedContentTransformer.php
- style.css
- add series teaser widget to frontpage
> Ivd 646/add series teaser widget to frontpage

- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Adapters/Wp/Pages/PageAdapter.php
- style.css
- hide translations if not published
> IVD-594/hide translations if not published

- composer.lock
- src/Repositories/WhiteAlbum/RedirectRepository.php
- style.css
Parsing url, before looking up, to unify the insert and lookup requests
> BUGFIX - Fixing issue with insert warnings in backend.

- src/Controllers/App/SitemapController.php
- style.css
Updated the API output to send the total amount of pages for a given sitemap type for Nuxt.
> Patch - Total sitemap pages in api output

- src/Controllers/App/SitemapController.php
- style.css
Removing meta query for 'exclude from web'
> Bugfix - Slow Sitemap

- composer.lock
- src/Adapters/Cxense/Search/DocumentAdapter.php
- src/Adapters/Wp/App/InstagramCompositeAdapter.php
- src/Adapters/Wp/App/PinterestCompositeAdapter.php
- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Models/Base/Composites/Composite.php
- src/Models/Contracts/Composites/CompositeContract.php
- src/Models/Gds/Composite.php
- style.css
> WILL-1101/FEATURE: Shell articles

- composer.json
- composer.lock
- src/Actions/ActionsBootstrap.php
- src/Actions/Backend/RedirectHandler.php
- style.css
Updating WP Bonnier Redirect to 4.7.1
> WILL-1203 - Adding filter to allow redirects being created for web-excluded posts.

- composer.json
- composer.lock
- functions.php
- src/Bootstrap.php
- src/Controllers/Admin/NotFoundController.php
- src/Controllers/App/RouteController.php
- src/Database/DB.php
- src/Database/Migrations/CreateNotFoundTable.php
- src/Database/Migrations/Migrate.php
- src/Database/Migrations/Migration.php
- src/Database/Query.php
- src/Exceptions/Database/DuplicateEntryException.php
- src/Exceptions/Database/MigrationException.php
- src/Models/Admin/NotFound.php
- src/Notifications/Mailer.php
- src/Notifications/NotFoundRegistered.php
- src/Repositories/NotFoundRepository.php
- src/Views/notFoundTable.php
- style.css
Adding logging of 404 errors, also adding notifications for when a URL exceeds threshold.
> WILL-1120 - 404 overview

- src/Controllers/App/RouteController.php
- style.css
Updating Route Resolver to fail when invalid url (`//invalid-url`) is submitted.
> WILL-1484 - Return 404 on invalid URLs

- composer.json
- composer.lock
- src/Actions/ActionsBootstrap.php
- src/Actions/Universal/SitemapFilters.php
- style.css
- tests/Unit/Actions/Universal/SitemapFiltersTest.php
Updating WP Bonnier Sitemap to 1.2.0 to take advantage of new filters for permalinks being saved.
> WILL-1573 - Stripping subdomains from sitemap permalinks

- composer.json
- composer.lock
- src/Adapters/Cxense/Search/AuthorAdapter.php
- src/Adapters/Wp/Root/AuthorAdapter.php
- src/Controllers/App/RouteController.php
- src/Models/Base/Root/Author.php
- src/Models/Contracts/Root/AuthorContract.php
- src/Repositories/WpModelRepository.php
- src/Transformers/Api/Root/AuthorTransformer.php
- src/Transformers/Api/Root/Partials/AuthorDetailsTransformer.php
- style.css
Adding composite teasers to available includes and bugfixing profile picture fetching
> WILL-1657 - Implement CompositeTeasers for authors

- composer.json
- composer.lock
- src/Bootstrap.php
- style.css
Updating WP Bonnier Sitemap to 1.3.0 to include authors in sitemaps.
> WILL-1681 - Authors in sitemaps

- src/Actions/ActionsBootstrap.php
- src/Actions/Backend/MediaThumbs.php
- style.css
Fixes so the backend appends imgix params to media thumbs instead of loading full size images (verry slow and costly)
> Feature: Imgix media thumbs

- src/Adapters/Wp/Root/FileAdapter.php
- src/Adapters/Wp/Root/ImageAdapter.php
- style.css
Better handling of images either being arrays or objects, when passed around adapters.
> WILL-1773 - Getting alt text of images

- composer.lock
- src/Repositories/WhiteAlbum/RedirectRepository.php
- style.css
Redirects to destinations outside the current domain, will be absolute instead of relative.
> WILL-1360 - WA Route Resolving now respects external redirects

- src/Transformers/Api/Composites/CompositeTeaserTransformer.php
- style.css
At some point, we added:
```php
/**
* List of resources possible to include
*
* @var array
*/
protected $availableIncludes = [
'vocabularies'
];
```
So I thought it would be a good idea to actually implement the include...
> Noticket - Adding `includeVocabularies`

- composer.json
- composer.lock
- src/Bootstrap.php
- style.css
Adding filter to hide internal tags from sitemap
> WILL-1659 - Remove bannerblock from sitemap

- src/Factories/AbstractModelFactory.php
- style.css
Fixes issues where APP_CHILD_THEME could break if the casing in the env was wrong
> Fix APP_CHILD_THEME casing

- src/Commands/GDS/XmlImport.php
- src/Commands/GDS/XmlParser.php
- style.css
GDSD-7: Bulk import, set locked_content=false for images and pdf-file, rename imported folder if it already exists
> Gdsd 7/xml import

- src/ACF/Brands/BOB.php
- src/ACF/Brands/Brand.php
- src/ACF/Brands/BrandFactory.php
- src/ACF/Brands/COS.php
- src/ACF/Brands/GDS.php
- src/ACF/Brands/HIS.php
- src/ACF/Brands/ILL.php
- src/ACF/Brands/VOL.php
- src/Actions/Universal/PageTemplates.php
- src/Models/ACF/Composite/CompositeFieldGroup.php
- style.css
Changing display hint for teaser list and galleries on voldemort.
> VOLD-71/Adding Voldemort as a brand with multiple subbrands.

- src/Models/WpTaxonomy.php
- style.css
to be able to use /wp-json/wp/v2/composites?editorial_type=xxx
> APPS-44: Added show_in_rest to WpTaxonomy

- src/Transformers/Api/Root/AuthorTransformer.php
- style.css
Add author email to author transformer.
> VOLD-95 Set author email on transformer

- src/Actions/Universal/PageTemplates.php
- src/Adapters/Wp/Pages/Contents/Types/AuthorOverviewAdapter.php
- src/Models/ACF/Fields/Wysiwyg.php
- src/Models/ACF/Page/PageFieldGroup.php
- src/Models/Base/Pages/Contents/Types/AuthorOverview.php
- src/Models/Contracts/Pages/Contents/Types/AuthorOverviewContract.php
- src/Transformers/Api/Root/Contents/Types/AuthorOverviewTransformer.php
- style.css
Remove unused fields for author overview. Add wysiwyg editor for editor fields title and description.
> Feature: add editor fields to author overview

- src/ACF/Brands/IFO.php
- src/Adapters/Wp/Composites/Contents/Types/AssociatedCompositesAdapter.php
- src/Adapters/Wp/Composites/Contents/Types/RecipeAdapter.php
- src/Models/Base/Composites/Contents/Types/AssociatedComposites.php
- src/Models/Contracts/Composites/Contents/Types/AssociatedCompositesContract.php
- src/Transformers/Api/Composites/Includes/Contents/Types/AssociatedCompositesTransformer.php
- style.css
+ IFD-190/Recipe: Default: True: show_meta_info_in_header_and_teaser
> Ifd 187/nyt displayhint på associated composites widget

- src/ACF/Brands/BOB.php
- src/ACF/Brands/Brand.php
- src/ACF/Brands/COS.php
- src/ACF/Brands/GDS.php
- src/ACF/Brands/HIS.php
- src/ACF/Brands/IFO.php
- src/ACF/Brands/ILL.php
- src/ACF/Brands/VOL.php
- src/Models/ACF/User/UserFieldGroup.php
- src/Models/WpUserProfile.php
- style.css
Add language support on user/author title field
> Ifd 306/necessary changes to author page (backend)

- assets/js/acf/fields/markdown-editor.js
- style.css
Tickets in Jira:
[WILL-2362](https://bonnierpublications.atlassian.net/browse/WILL-2362)
[WILL-2185](https://bonnierpublications.atlassian.net/browse/WILL-2185)
> WILL-2362/Remove rel=follow from markup when it is set

- src/ACF/Brands/Brand.php
- style.css
> IFD-234/Add-taxonomy-choices-to-teaser-list

- src/Adapters/Cxense/Search/DocumentAdapter.php
- style.css
Adding dynamic organisation prefix to new cxense fields.
> Ifd 319/map new cxence fields to searchresult mostpopular i api backend

- src/ACF/Brands/IFO.php
- src/Models/WpComposite.php
- style.css
> Ifd 289/article edit and preview  text issues

- src/Adapters/Wp/Composites/Contents/StoryAdapter.php
- style.css
> Ifd 288/associated composites with display hint story list

- src/Adapters/Cxense/Search/DocumentAdapter.php
- src/Helpers/VideoMetaHelper.php
- style.css
different bug fixes related to cxense output transformations...
> IFD-432/ANNONCE-label-on-ALL-articles-in-search-result

- src/Models/ACF/Composite/CompositeFieldGroup.php
- style.css
Activate 7 new calculators in the backend dropdown menu.
> IFD-411/Fix-last-7-calculators-from-old-iform

- src/Adapters/Wp/Root/FileAdapter.php
- style.css
increasing aws file download timeout from 1 hour to 6 hours.
> IFD-400/Download-af-PDF-virker-ikke-alle-steder

- src/Adapters/Wp/Composites/CompositeAdapter.php
- style.css
if publishedAt er større end updatedAt, skal updatedAt være publishedAt
> APPS-253/APP---HIS--Articles-are-not-shown

- src/Adapters/Cxense/Search/CommercialAdapter.php
- src/Adapters/Cxense/Search/DocumentAdapter.php
- style.css
moving bod-commercial-label + format to dynamick organisation fields with dynamic prefixes
> IFD-415/wrong-cxense-metatag

- composer.json
- composer.lock
- style.css
new wp-cxense with license mit test
> Ifd 415/wrong cxense metatag

- .circleci/config.yml
- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Models/Base/Terms/Category.php
- src/Models/Contracts/Terms/CategoryContract.php
- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- src/Transformers/Api/Terms/Category/Partials/CategoryDetailsTransformer.php
> WYPE-136/Additional-category-information-in-API-endpoint-for-Wype

- composer.lock
- style.css
update wp-bonnier-sitemaps plugin to version 1.5.5
> Ifd 370/missing author urls in the sitemap

- src/Controllers/App/ContentController.php
- src/Helpers/SortBy.php
- style.css
Adding categories parameter to cxense most popular endpoint
> IFD-409/Extra-teasers-widgets-and-banners-below-content

- src/Helpers/CompositeHelper.php
- style.css
if multiple associated composites on a story only save parent from the first one!
> WILL-2706/Story-list-bug-has-reappeared-on-I-FORM

- src/Adapters/Cxense/Search/CategoryAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Models/Base/Terms/Category.php
- src/Models/Contracts/Terms/CategoryContract.php
- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- style.css
adding with=content-teasers-count:include_children(true)
for getting total teasercount when including children for pagination etc.
> VOLD-488/Category-pages-only-show-a-fraction-of-available-content

- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Adapters/Wp/Root/AuthorAdapter.php
- src/Adapters/Wp/Terms/Tags/TagAdapter.php
- src/Helpers/SortBy.php
WILL-2071/Exclude-from-web-doesnt-work
> WILL-2071/Exclude-from-web-doesnt-work

- src/Controllers/App/RouteController.php
- style.css
Adding this type of preview url
/om-i-form/testings?preview_id=61859&preview_nonce=bb9bf59bb9&preview=true&nonce=6b1d3603dd&cacheClear=true&uid=0f8af3424045f5b583fa0775541a723c
to the resolveroute controller methods.
> WILL-2417/purge-cache-in-preview

- src/Adapters/Wp/Root/AuthorAdapter.php
- style.css
> Ifd 400/download af pdf virker ikke alle steder

- assets/js/acf/fields/video-api.js
- functions.php
- src/Models/ACF/Composite/CompositeFieldGroup.php
> WILL-2511/Video-schema-markup

- .circleci/config.yml
- composer.json
- composer.lock
- src/ACF/Brands/BOB.php
- src/Actions/Universal/PageTemplates.php
- style.css
Enabling Recipe template + Recipe widget on BOB/Scandiliv.
> Vold 670/recipe schema missing on scandiliv se

- src/ACF/Brands/ALL.php
- src/ACF/Brands/BrandFactory.php
- src/Actions/Universal/PageTemplates.php
- style.css
Adding "ALL" as wype class, ALL because wype changes name and its more generic.
> W30W-1/Establish-domain-and-sites

- src/ACF/Brands/ALL.php
- src/ACF/Brands/BOB.php
- src/ACF/Brands/BrandFactory.php
- src/ACF/Brands/BrandInterface.php
- src/ACF/Brands/COS.php
- src/ACF/Brands/GDS.php
- src/ACF/Brands/HIS.php
- src/ACF/Brands/IFO.php
- src/ACF/Brands/ILL.php
- src/ACF/Brands/VOL.php
- style.css
Enable recipe widget for BOL + BOM in voldemort brand class.
> VOLD-898+1145/Add-recipe-widget-to-backend
