- composer.json
- composer.lock
- src/Commands/Cleanup.php
- src/Commands/CommandBootstrap.php
- src/Controllers/App/RouteController.php
- style.css
This script makes it possible to delete a bunch of articles based on a CSV containing a list of URL's of the articles that needs to be deleted and the corresponding URL it needs to redirect to.
The CSV MUST only contain two columns and the first row MUST contain `from` and `to` in the two columns respectively.
Run the script with:
`wp willow cleanup delete articles-to-be-deleted.csv`
By default the csv delimiter is a comma (`,`), but can be changed with the delimiter option:
`wp willow cleanup delete articles-to-be-deleted.csv --delimiter=';'`
> IVD-218 - Deleting content from CSV

- composer.lock
- Updating WP Bonnier Cache to 2.0.1
> IVD-352 - Clear all from cache

- composer.json
- composer.lock
- style.css
Since filtering in the WordPress API was removed in 4.7, we've added a plugin to add this functionality again.
> IVD-321 - Custom Taxonomy Filtering

- composer.lock
- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Adapters/Wp/Pages/PageAdapter.php
- style.css
If no widgets are added to a Page in WordPress, `$this->acfFields[AcfName::GROUP_PAGE_WIDGETS]` would return `false` instead of an empty array, which would cause the method `getContents()` to fail, because it would try to map on a collection containing one value that is `false`.
Hence a fallback to null, if a falsey value is returned on PageAdapter and CompositeAdapter, to avoid errors being thrown when no ACF Fields are set.
> Bugfix - Pages fails when no ACF Fields are set on it.

- composer.lock
- src/Adapters/Wp/Root/ColorPaletteAdapter.php
- style.css
WordPress might save a serialised object instead of a json encoded string, and will deserialise it on retrieval.
Therefore we need to test if the property is a string, it needs to be decoded, otherwise it's ready for use.
> Bugfix - Color Palette

- src/Transformers/Api/Composites/Includes/Contents/Types/GalleryTransformer.php
- style.css
If a gallery contained an empty image, an error would be thrown.
This fix is rejecting all invalid images from the gallery.
> Bugfix - Fixing error thrown in galleries

- .circleci/config.yml
Circle-CI has screwed up latest build of there image. Therefor I've added the there latest working sha value, so we can use it until they fix the issue.
I reported the issue to Circle-CI.
> Hotfix for circleci

- src/Controllers/App/RouteController.php
- style.css
We had an issue where, if the category slug was identical to the composite slug, the route resolver would return 404.
I've updated the RouteController to not check if the path part is a category, if it's the last item in the path and we are testing for composites.
In that way, we'll be able to support categories and composites with identical slugs.
> IVD-479 - Category and composite slug collides 

- src/Commands/AuthorFix.php
- style.css
+ added author clean up WP CLI command
examples:
`
wp contenthub editor author fix da 3`
lang: da
userId to replace default user with: 3
`
wp contenthub editor author fixAll`
> IVD-470/feature: added author clean up WP CLI command

- src/Adapters/Wp/Composites/Contents/Types/GalleryAdapter.php
- style.css
Fixing the following error:
`Uncaught TypeError: Argument 1 passed to Bonnier\Willow\Base\Adapters\Wp\Root\GalleryImageAdapter::__construct() must be of the type array, boolean given, called in /home/forge/api.illvid.dk/web/app/themes/willow-base-theme/src/Adapters/Wp/Composites/Contents/Types/GalleryAdapter.php on line 33 and defined in /home/forge/api.illvid.dk/web/app/themes/willow-base-theme/src/Adapters/Wp/Root/GalleryImageAdapter.php:21`
> Bugfix - Fixing a fatal error thrown

- composer.lock
- src/Actions/Backend/PostSlugChange.php
- style.css
The closes category was used to generate a redirect, instead of the actual URL of that category. This has now been fixed.
> WILL-963 - Unpublishing an article creates invalid redirect

- src/Adapters/Wp/Composites/CompositeAdapter.php
- src/Adapters/Wp/Pages/PageAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Adapters/Wp/Terms/Tags/TagAdapter.php
- style.css
The mapWithKeys callback, must ALWAYS return an array. If it returns null, it throws a warning.
> Bugfix - Invalid return value used in mapWithKeys

- src/Controllers/App/SitemapController.php
- style.css
When calculating the tags to be excluded, all empty tags should be part of the calculation, otherwise all empty tags will NOT be excluded.
> HIS-47 - Bugfix tag counting

- src/Controllers/App/RouteController.php
- style.css
Updating `preg_match` to allow for an optional trailing slash. This will then be redirected by the `shouldPathRedirect` method.
> HIS-51 - Trailings slash on tag pages should redirect

- .circleci/config.yml
- composer.lock
- src/Controllers/App/RouteController.php
- style.css
Updating route resolver to not use `get_page_by_path` since it just returned the first match, instead of all matches or matches that also had same locale.
Now, pages are being found in the same way Contenthub Composites are found, which uses the locale in the query.
> WILL-1579 - Page slugs resolved incorrectly across languages

- src/Repositories/WpModelRepository.php
- style.css
Instead of sometimes returning an array, `WPModelRepository->getPost()` will now always return a WP_Post object or null.
> Bugfix - WPModelRepository always returns WP_Post or null

- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryTeaserAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryTranslationAdapter.php
- src/Adapters/Wp/Terms/Tags/TagAdapter.php
- src/Adapters/Wp/Terms/Tags/TagTeaserAdapter.php
- src/Adapters/Wp/Terms/Tags/TagTranslationAdapter.php
- src/Adapters/Wp/Terms/Vocabulary/VocabularyAdapter.php
- style.css
Wrapping titles and names from terms in htmlspecialchars_decode, to ensure that ampersands are outputtet in plaintext, instead of being HTML encoded.
> WILL-1765 - HTML encoded special characters in titles

- src/Controllers/App/RouteController.php
- style.css
Drafted pages has a slightly different query parameter structure to contenthub composites, which has now been supported to return drafted pages as well as drafted composites.
> WILL-717 - Support drafted pages in route resolver

- functions.php
- src/Bootstrap.php
- src/Controllers/Root/PageController.php
- style.css
In order for editors to view drafted pages, we needed to overwrite the default REST controller and ensure the `check_read_permission` would return true.
> WILL-717 - Making page drafts public

- assets/js/acf/fields/taxonomy-fields.js
- style.css
Categories can not be updated as the select boxes was disabled an alternative to this is to disable other options than the select itself.
also used readonly instead of disabled as it is less intrusive.
> Feature: disable other options in select box

- src/Models/ACF/Page/PageFieldGroup.php
- style.css
The role filtering will cause more problems than actually helping, during i was setting a test page for costume up, was not a pleasant experience having this prefiltered.
> Chore: remove role filtering on author overview

- src/Traits/UrlTrait.php
- style.css
When we strip canonical urls we expect the format to be api.beta.illvid.dk. Due to cloudflare we have changed to the format api-beta.illvid.dk therefor the strip function needs to be updated.
> Chore: strip api respect new url format

- src/ACF/Brands/Brand.php
- src/ACF/Brands/IFO.php
- style.css
It is only the REQUIRED option for the images repeater + image that should be removed.
Else we cant import/migrate data that does not have images.
> IFD-272/Remove-images-from-File-widget-on-IFORM

- src/ACF/Brands/BOB.php
- src/ACF/Brands/Brand.php
- src/ACF/Brands/COS.php
- src/ACF/Brands/GDS.php
- src/ACF/Brands/HIS.php
- src/ACF/Brands/IFO.php
- src/ACF/Brands/ILL.php
- src/ACF/Brands/VOL.php
- src/Helpers/AcfName.php
- src/Helpers/SortBy.php
- src/Models/ACF/Page/SortByFields.php
- style.css
Adding more advanced options to teaserlist taxonomy sortby functions
- adding "include category children" True/False checkbox
- adding "Category/tag relation" select('And', 'Or')
- adding "Category operator" select('In', 'Not in'). 
- NOTE no 'And' here, an article cant be i more than one category anyway.
- adding "Tags operator" select('And', 'In', 'Not in')
- changed "tax_query" to match new values and output.
- NOTE only changed if using advanced custom taxonomy in teaserlist like iform :)
- remove from other brands than IFO.
> IFD-234/Add-taxonomy-choices-to-teaser-list

- src/Adapters/Cxense/Search/CategoryAdapter.php
- src/Adapters/Wp/Terms/Categories/CategoryAdapter.php
- src/Models/Base/Terms/Category.php
- src/Models/Contracts/Terms/CategoryContract.php
- src/Transformers/Api/Terms/Category/CategoryTransformer.php
- style.css
adding content-teasers:include_children(true) to category api endpoint to be able to include children posts of the category.
> IFD-345/Category-pages-include-child-and-grandchild
